version: '3.9'

services:

    traefik:
        image: traefik:v2.3
        restart: unless-stopped
        ports:
            - target: 80
              published: 80
              mode: host
            - target: 443
              published: 443
              mode: host
            - target: 3333
              published: 3333
              mode: host
            - target: 3334
              published: 3334
              mode: host
            - target: 8080
              published: 8080
              mode: host
            - target: 34197
              published: 34197
              protocol: udp
              mode: host
        networks:
            - proxy-traefik
            - docker-proxy-network
        volumes:
            - ./traefik.toml:/traefik.toml
            - ./conf:/opt/traefik/conf
            - ${SSL_CERT_PATH:?SSL_CERT_PATH NOT SET !}:/opt/traefik/certs

    docker-proxy:
        image: tecnativa/docker-socket-proxy
        restart: unless-stopped
        environment:
            - ALLOW_RESTARTS=0
            - AUTH=0
            - BUILD=0
            - COMMIT=0
            - CONFIGS=0
            - CONTAINERS=1
            - DISTRIBUTION=0
            - EVENTS=1
            - EXEC=0
            - IMAGES=0
            - INFO=0
            - NETWORKS=1
            - NODES=0
            - PING=1
            - PLUGINS=0
            - POST=0
            - SECRETS=0
            - SERVICES=1
            - SESSION=0
            - SWARM=1
            - SYSTEM=0
            - TASKS=1
            - VERSION=1
            - VOLUMES=0
        networks:
            - docker-proxy-network
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    proxy-traefik:
        name: proxy-traefik
    docker-proxy-network:
        internal: true

volumes:
    composer-cache-v2:
        name: composer-cache-v2

    yarn-cache-v2:
        name: yarn-cache-v2

    npm-cache:
        name: npm-cache
