[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[serversTransport]
  insecureSkipVerify = false

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[providers]
  [providers.file]
    directory = "/opt/traefik/conf/"
    watch = true
  [providers.docker]
    watch = true
    endpoint = "tcp://docker-proxy:2375"
    exposedByDefault = false
    network = "proxy-traefik"

[api]
  insecure = true
  dashboard = true
  debug = true

[log]
  level = "DEBUG"
